In [ ]:
#variable and string
a=10
print("i am", a ,"years old")


i am 10 years old


In [ ]:
#arithmatic ops on int variable
a=int(input("enter a value"));
b=int(input("enter b value"));
c=a+b;
print(c);

enter a value12
enter b value20
32


In [1]:
a=int(input("enter a value"))
b=float(input("enter b value"))
print(a,b)

enter a value100
enter b value20.903
100 20.903


In [ ]:
a=int(input("enter a value"));
b=int(input("enter b value"));
c=a-b;
print(c);


enter a value222
enter b value111
111


In [ ]:
a=int(input("enter a value"));
b=int(input("enter b value"));
c=a*b;
print(" product is",c);

enter a value10
enter b value20
 product is 200


In [ ]:
#arithmetic operators
a=int(input("enter a value"));
b=int(input("enter b value"));
print("quotient is",a/b)
print("remainder is",a%b)
print("product is",a*b)
print("power is",a**1b)

enter a value13
enter b value14
quotient is 0.9285714285714286
remainder is 13
product is 182
power is 3937376385699289


In [ ]:
#get salary from the user,if the salary is more than 50,000,there is a 10% tax reduction,print his final salary.
salary=int(input("enter salary   "))
if (salary>=50000):
  salary= salary-(salary*0.1)
  print("salary is",salary);
else:
  print("salary is greater than 50,000");



enter salary   640000
salary is 576000.0


In [ ]:
#get the salary from the user, if the salary is more than or equal to 50,000,apply 10% tax deduction.if the salary is less than 50,000 apply 5% tax,if the salary is  70,000,apply 12% tax,if the salary exeeds 1 lakh print you are promoted to next level
salary=int(input("enetr the salary :"))
if(salary<=50000):
  print("salary is",salary-(salary*(5/100)))
elif(salary>=5100 and salary<=70000):
  print("salary is",salary-(salary*(0.1)))
elif(salary>=71000 and salary<=100000):
  print("salary is",salary-(salary*(12/100)))
else:
  print("congrats!! you are promoted")

enetr the salary :72000
salary is 63360.0


In [2]:
a=int(input("enter a value"))
if (a<100):
  print("less than 100")
else:
  print("greater than 100")

enter a value120
greater than 100


In [ ]:
#range
r=range(1,11)
a=int(input("enter the value"))
for i in  r:
  print(a,"x",i,"=",a*i)

enter the value108
108 x 1 = 108
108 x 2 = 216
108 x 3 = 324
108 x 4 = 432
108 x 5 = 540
108 x 6 = 648
108 x 7 = 756
108 x 8 = 864
108 x 9 = 972
108 x 10 = 1080


In [ ]:
print("hello world")

hello world


In [ ]:
#while loop
a=int(input("enter the number"))
i=1
while(i<11):
   print(a,"x",i,"=",a*i)
   i=i+1

enter the number11
11 x 1 = 11
11 x 2 = 22
11 x 3 = 33
11 x 4 = 44
11 x 5 = 55
11 x 6 = 66
11 x 7 = 77
11 x 8 = 88
11 x 9 = 99
11 x 10 = 110


In [ ]:
#create a heterogenious list
l1=['prani',20.2,'hello','true']
for i in l1:
  print(i)

prani
20.2
hello
true


In [ ]:
#insertion at middle
l1.insert(4,'hi')#listname.insert(index,element)
print(l1)

['prani', 20.2, 'hello', 'true', 'hi', 'apppended']


In [ ]:
#concatination
l2=['python','data']
print(l1+l2)

['prani', 20.2, 'hello', 'true', 'hi', 'apppended', 'python', 'data']


In [ ]:
#append-adds element from the last of the list
l1.append("apppended") #listname.append(element)
print(l1)

['prani', 20.2, 'hello', 'true', 'apppended']


In [ ]:
#entend-adds the two lists to first list
l1.extend(l2)#l1+l2
print(l1)#listname.extend(second list)

['prani', 20.2, 'hello', 'true', 'hi', 'apppended', 'python', 'data']


In [ ]:
#remove -a keyword used to remove a element from the list
l1.remove('true')#listname.remove(element)
print(l1)

['prani', 20.2, 'hi', 'apppended', 'python', 'data']


In [ ]:
#pop-removes the last element from the list
l1.pop(3)#listname.pop(index)
print(l1)

['prani', 20.2, 'hi', 'python', 'data']


In [ ]:
#clear-clears the list
l1.clear()#listname.clear()
print(l1)

[]


In [ ]:
#create a list of random integers of 10 elements,print thier squares,save this squares in a new list
l1=[11,12,13,14,15,16,17,18,19,20]
l2=[]
for i in l1:
  l2.append(i**2)
print(l2)


[121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [ ]:
#list comprehension
#newlist=[output for statement]
l1=[11,12,13,14,15,16,17,18,19,20]
l2=[i*i for i in l1]
print(l2)

[121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [ ]:
#newlist=[output for statement if statement]
l1=[11,12,13,14,15,16,17,18,19,20]
l2=[i*i for i in l1 if i>15]
print(l2)

[256, 289, 324, 361, 400]


In [ ]:
#list comprehension using if-else
#newlist=[(st of if) if (cond) else (st of else) for]
l1=[11,12,13,14,15,16,17,18,19,20]
l2=[i*i if (i>15) else 'x' for i in l1]
print(l2)


['x', 'x', 'x', 'x', 'x', 256, 289, 324, 361, 400]


In [ ]:
#take the salary from the user, if the salary is lessthan 50k then 10% tax otherwise 15% tax
l1=int(input("enter the salary  "))
l2=[l1-(l1*0.1) if l1<50000 else l1-(l1*(15/100))]
print(l2)

enter the salary  60300
[51255.0]


In [ ]:
l1=[50000,60000,20000,12000,59000]
l2=[i-i*0.1 if i<50000 else i-i*0.15 for i in l1]
print(l2)

[42500.0, 51000.0, 18000.0, 10800.0, 50150.0]


In [ ]:
#create dictionary
dict1={"mentor":'jwalitha',12:'likitha',13:'ramya',14:'lavanya'}
print(dict1)

{'mentor': 'jwalitha', 12: 'likitha', 13: 'ramya', 14: 'lavanya'}


In [ ]:
print(dict1.keys())
print(dict1.values())

dict_keys(['mentor', 12, 13, 14])
dict_values(['jwalitha', 'likitha', 'ramya', 'lavanya'])


In [ ]:
print(dict1[14])

lavanya


In [ ]:
#nested dictionary
dict3={"department":"CSE","details":{"year":"II","section":"D","count":71}}
print(dict3["details"]["section"])

D


In [ ]:
dict3={"department":"CSE","details":{"year":"II","section":"D","count":71}}
print("year is",dict3["details"]["year"])
print("section is",dict3["details"]["section"])
print("count is",dict3["details"]["count"])

year is II
section is D
count is 71


In [ ]:
l1=["prani","joe","rohi","hello"]
l2=[11,12,13,14]
new_zip=(zip(l2,l1))
for i in new_zip:
  print(i)


(11, 'prani')
(12, 'joe')
(13, 'rohi')
(14, 'hello')


In [ ]:
l1={"prani","joe","rohi","hello"}
l2={11,12,13,14}
new_dict=(zip(l2,l1))
print(dict(new_dict))

{11: 'joe', 12: 'prani', 13: 'rohi', 14: 'hello'}


In [ ]:
#numpy code1
import numpy as np
A=np.array([[[1,2,3,4],[6,7,8,9]],[[10,11,12,13],[14,15,16,17]]]) #1D array
#elements in each row is equal to colums
print(A.ndim)
print(A.shape)
print(A)

3
(2, 2, 4)
[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[10 11 12 13]
  [14 15 16 17]]]


In [ ]:
A=np.ones((2,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
A=np.ones((4,3))#groups,rows,columns
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
A=np.zeros((2,4,3))#groups,rows,columns
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2)#START,STEP,STOP
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:

#print all the numbers that are divisible by 8,using a range function between 1 and 1000
A=np.arange(8,1001,8)
print(A)
print(type(A))

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
A=np.arange(1,10001,8)
print(A)
print(type(A))

[   1    9   17 ... 9977 9985 9993]
<class 'numpy.ndarray'>


In [ ]:
A=np.linspace(48,59,20)
print(A)

[48.         48.57894737 49.15789474 49.73684211 50.31578947 50.89473684
 51.47368421 52.05263158 52.63157895 53.21052632 53.78947368 54.36842105
 54.94736842 55.52631579 56.10526316 56.68421053 57.26315789 57.84210526
 58.42105263 59.        ]


In [ ]:
A=np.linspace(3,2,12)#splitting a range into n numbers with common differences
print(A)

[3.         2.90909091 2.81818182 2.72727273 2.63636364 2.54545455
 2.45454545 2.36363636 2.27272727 2.18181818 2.09090909 2.        ]


In [ ]:
#study tuples and sets
#documentation
#qr code task